# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20180505_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
