# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_supply_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supply', to='shops.Buyer'),
            preserve_default=False,
        ),
    ]
